added status validation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,8 +43,23 @@ jobs:
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
-              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T out/out.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}"
-              curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish"
+              UPLOAD_RESULT=(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T out/out.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
+              if [ "$(echo $UPLOAD_RESULT | jq -r .uploadState)" == "FAILURE" ]; then
+                echo *********************************************************************
+                echo Package validation failed
+                echo Error: $(echo $result | jq .itemError | jq -r first.error_code)
+                echo Detail: $(echo $result | jq .itemError | jq -r first.error_detail)
+                echo *********************************************************************
+                exit 1
+              fi
+              PUBLISH_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish" | jq .uploadState)
+              if [ "$(echo $PUBLISH_RESULT | jq -r .status)" != "["OK"]" ]; then
+                echo *********************************************************************
+                echo Status: $(echo $PUBLISH_RESULT | jq -r .status)
+                echo Detail: $(echo $PUBLISH_RESULT | jq -r .statusDetail)
+                echo *********************************************************************
+                exit 1
+              fi
             fi
 
 
