fixed config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,54 +1,52 @@
 version: 2
 
-&src-cache-key src-{{ .Branch }}-{{ .Revision }}
-&npm-dependencies-cache-key npm-dependencies-{{ checksum "package.json" }}
-&npm-prod-package-cache-key prod-package-{{ .Branch }}-{{ .Revision }}
-&npm-canary-package-cache-key canary-package-{{ .Branch }}-{{ .Revision }}
+key: &src-cache-key src-{{ .Branch }}-{{ .Revision }}
+key: &npm-dependencies-cache-key npm-dependencies-{{ checksum "package.json" }}
+key: &npm-prod-package-cache-key prod-package-{{ .Branch }}-{{ .Revision }}
+key: &npm-canary-package-cache-key canary-package-{{ .Branch }}-{{ .Revision }}
 
-&upload-and-publish
-  steps:
-      - run:
-          name: "Install Dependencies"
-          command: |
-            sudo apt-get update
-            sudo apt-get -y install curl jq
-      - restore_cache:
-          key: *npm-prod-package-cache-key
-      - restore_cache:
-          key: *npm-canary-package-cache-key
-      - run:
-          name: "Upload Extension to the Google Chrome Store"
-          command: |
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              export ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
-              UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T $PACKAGE_NAME -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
-              echo Package uploaded
-              echo $UPLOAD_RESULT
-              if [ "$(echo $UPLOAD_RESULT | jq -r .uploadState)" == "FAILURE" ]; then
-                echo *********************************************************************
-                echo Package validation failed
-                echo Error: $(echo $result | jq .itemError | jq -r first.error_code)
-                echo Detail: $(echo $result | jq .itemError | jq -r first.error_detail)
-                echo *********************************************************************
-                # exit 1
-              fi
-            fi
-      - run:
-          name: "Publish Extension to the Google Chrome Store"
-          command: |
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              PUBLISH_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish")
-              echo Package published
-              echo $PUBLISH_RESULT
-              if [ "$(echo $PUBLISH_RESULT | jq -r .status)" != "["OK"]" ]; then
-                echo *********************************************************************
-                echo Status: $(echo $PUBLISH_RESULT | jq -r .status)
-                echo Detail: $(echo $PUBLISH_RESULT | jq -r .statusDetail)
-                echo *********************************************************************
-                # exit 1
-              fi
-            fi
-
+steps: &upload-and-publish
+  - run:
+      name: "Install Dependencies"
+      command: |
+        sudo apt-get update
+        sudo apt-get -y install curl jq
+  - restore_cache:
+      key: *npm-prod-package-cache-key
+  - restore_cache:
+      key: *npm-canary-package-cache-key
+  - run:
+      name: "Upload Extension to the Google Chrome Store"
+      command: |
+        if [ "${CIRCLE_BRANCH}" == "develop" ]; then
+          export ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
+          UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T $PACKAGE_NAME -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID}")
+          echo Package uploaded
+          echo $UPLOAD_RESULT
+          if [ "$(echo $UPLOAD_RESULT | jq -r .uploadState)" == "FAILURE" ]; then
+            echo *********************************************************************
+            echo Package validation failed
+            echo Error: $(echo $result | jq .itemError | jq -r first.error_code)
+            echo Detail: $(echo $result | jq .itemError | jq -r first.error_detail)
+            echo *********************************************************************
+            # exit 1
+          fi
+        fi
+  - run:
+      name: "Publish Extension to the Google Chrome Store"
+      command: |
+        if [ "${CIRCLE_BRANCH}" == "develop" ]; then
+          PUBLISH_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID}/publish")
+          echo Package published
+          echo $PUBLISH_RESULT
+          if [ "$(echo $PUBLISH_RESULT | jq -r .status)" != "["OK"]" ]; then
+            echo *********************************************************************
+            echo Status: $(echo $PUBLISH_RESULT | jq -r .status)
+            echo Detail: $(echo $PUBLISH_RESULT | jq -r .statusDetail)
+            echo *********************************************************************
+            # exit 1
+          fi
+        fi
 
 jobs:
   install_dependencies:
@@ -128,7 +126,8 @@ jobs:
       - APP_ID: pekgbpmeppfghkiaaolmjhiooapokgbk
       - PACKAGE_NAME: out/canary.zip
     working_directory: /home/circleci/project
-    *upload-and-publish
+    steps:
+      *upload-and-publish
   upload_and_publish_prod:
     docker:
       - image: circleci/node:9.2.1
@@ -136,8 +135,8 @@ jobs:
       - APP_ID: pekgbpmeppfghkiaaolmjhiooapokgbk
       - PACKAGE_NAME: out/package.zip
     working_directory: /home/circleci/project
-    *upload-and-publish
-
+    steps:
+      *upload-and-publish
 
 workflows:
   version: 2
